language: node_js
before_script:
  - gem install bundler
  - bundle install
#  - gem install compass-validator
  - npm install -g grunt-cli
script: "grunt test"
# CSS doesn't validate, some props are experimantal / unstandardized
# script: "grunt test && ln -s _config/config.rb && compass validate"
