safe: true
lsi: false
pygments: true
source: .
exclude:
    [
        "*.json",
        "*.rb",
        "*.sublime-*",
        "*.yaml",
        "*.yml",
        "CNAME",
        "Gemfile*",
        "Gruntfile.js",
        "node_modules",
        "Procfile",
        "README.md",
    ]
encoding: "UTF-8"
