safe: true
lsi: false
pygments: true
source: .
exclude:
    [
        "*.sublime-*",
        "CNAME",
        "compass",
        "config.rb",
        "Gemfile*",
        "README.md",
        "submodules",
        "watch.sh"
    ]
encoding: UTF-8
