encoding: "UTF-8"
lsi: false
pygments: true
safe: true
source: .
url: 'http://jonsurrell.com'
markdown: redcarpet
exclude:
    [
        "*.sublime-*",
        "*.yaml",
        "*.yml",
        "CNAME",
        "Gemfile*",
        "Gruntfile.js",
        "node_modules",
        "README.md"
    ]
