# GH Pages Overrides
# These settings are forces by gh-pages
safe: true
lsi: false
pygments: true
source: .
# Settings
name: jonsurrell.com
url: http://jonsurrell.com
encoding: utf-8
markdown: redcarpet
redcarpet:
  extensions:
    - tables
    - strikethrough
exclude:
  - CNAME
  - Gemfile*
  - gulpfile.js
  - node_modules
  - package.json
  - README*
