branches:
  only:
    - master
encoding: "UTF-8"
lsi: false
pygments: true
safe: true
source: .
url: http://surrell.es
exclude:
    [
        "*.json",
        "*.rb",
        "*.sublime-*",
        "*.yaml",
        "*.yml",
        "CNAME",
        "Gemfile*",
        "Gruntfile.js",
        "node_modules",
        "Procfile",
        "README.md",
    ]
